### PR TITLE
Implement remoting Windows EventLog access

### PR DESCRIPTION
**Pull request by cosmo0920**
To confirm this, we should prepare Windows Firewall for RPC login and adding EventLog Readers group into accessing account:
https://help.sumologic.com/03Send-Data/Sources/01Sources-for-Installed-Collectors/Remote-Windows-Event-Log-Source/Preconfigure-a-Machine-to-Collect-Remote-Windows-Events

### CODE REVIEW

**Comment by cosmo0920** [comment]
## Create Windows Firewall rules for RPC login

Group policy editor for RPC login

 
## Add accessing user into EventLog Readers group

Management computer

Management computer EventLog Readers

**Comment by cosmo0920** [comment]
@ashie Any concerns?

**Comment by cosmo0920** [comment]
Ah! Remoting connection exception should be raised with specific exception to check whether reloading is needed or not....

**Review by ashie — APPROVED** [review]

**Comment by cosmo0920** [comment]
Let's merge! :muscle:

**Pull request merged**
