### PR TITLE
Do not override error code

### PR DESCRIPTION
**Pull request by kenhys**
There are some cases that Win32 API fails, but the error code is not get correctly (ErrorCode = 0)
This situation occurs because GetLastError is not called appropriately.

### CODE REVIEW

**Comment by cosmo0920** [comment]
This PR causes building failure.
Could you check about it?

**Comment by kenhys** [comment]
I'll check appveyor CI.

**Comment by kenhys** [comment]
Got it, it lacks initialization for err.

**Review by cosmo0920 — APPROVED** [review]
:+1:

AppVeyor and GitHub Actions CI tasks are green. :green_circle:

**Comment by cosmo0920** [comment]
Let's :shipit:!

**Comment by kenhys** [comment]
Is `rake gem:native && rake release` enough?

**Comment by cosmo0920** [comment]
We only publish non fat gem. Please _don't install fat gems_. 
Thanks for your work!

**Pull request merged**
