### PR TITLE
Handle error code 1813 (RESOURCE_TYPE_NOT_FOUND)

### PR DESCRIPTION
**Pull request by cosmo0920**
We should also treat error code 1813 on `get_message`'s error operation.

Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>

### CODE REVIEW

**Comment by cosmo0920** [comment]
@ashie @kenhys Any thoughts?

**Comment by ashie** [comment]
I'll create a new pull request to clean up it after merging this.

**Comment by cosmo0920** [comment]
> Almost same code exists below that. Probably it should be added to there too, shouldn't it?

I've fixed it.

**Comment by cosmo0920** [comment]
> By the way, does another ERROR_RESOURCE_XXX occurs? (if not, it's ok)
> 
> https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1700-3999-

Oh, I've overlooked them. NAME and DATA should be occurred. But when...?

**Pull request merged**
